### ISSUE TITLE
custom python lsp error: Error running timer: (error "Not enough arguments for format string")

### ISSUE THREAD

**Issue by nanakura** [jadestrong/lsp-copilot#12]
配置如下
```toml
[language-server.delance]
command = "delance-langserver"
args = ["--stdio"]
[[language]]
name = "python"
file-types = ["py", "pyi", "py3", "pyw", "ptl", "rpy", "cpy", "ipy", "pyt", { glob = ".python_history" }, { glob = ".pythonstartup" }, { glob = ".pythonrc" }, { glob = "SConstruct" }, { glob = "SConscript" }]
language-id = "python"
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
language-servers = [ "delance" ]
```
出现这样的报错：
![image](https://github.com/user-attachments/assets/da57c7f5-5796-4b46-9356-23a73fffe822)
