### ISSUE TITLE
Lsp copilot startup exception under python-ts-mode

### ISSUE THREAD

**Issue by jiahut** [jadestrong/lsp-copilot#9]
window 11 

> pip install python-lsp-server

lsp-copliot configuration

``` toml
[[language]]
name = "python"
file-types = ["py", "pyi", "py3", "pyw", "ptl", "rpy", "cpy", "ipy", "pyt", { glob = ".python_history" }, { glob = ".pythonstartup" }, { glob = ".pythonrc" }, { glob = "SConstruct" }, { glob = "SConscript" }]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
language-servers = ["ruff", "jedi", "pylsp"]

```

When starting a single python file, `M-x lsp-copilot-find-definition` `*Message*` reports an error:

```
Lsp copilot agent started.
LSP-COPILOT :: Connected to "".
LSP-COPILOT :: Language server "" not support "textDocument/definition". [2 times]

```

**Comment by jadestrong** [comment]
It seems `"ruff", "jedi", "pylsp"` cannot found. How did you configure these server?

**Comment by jadestrong** [comment]
```
[language-server.pylsp]
command = "pylsp"
```
It should be configured like this. And `pylsp` can be accessable.

**Comment by jiahut** [comment]
According to your configuration, add

``` toml
[language-server.pylsp]
command = "pylsp"
```

python is working correctly.

Oddly enough, configuring go only works with the following
configuration



``` toml


[[language]]
name = "go"
file-types = ["go"]
roots = ["go.work", "go.mod"]
language-servers = [ "gopls"]


```
